### ISSUE TITLE
Clarify that the WCS information is stored in the header of the FITS file

### ISSUE THREAD

**Issue by wmwv** [mwvgroup/Tutorials#3]
The WCS information is stored in the header  of the FITS file.  You can read it yourself.  It will most likely be stored in the form of CRVAL*, CRPIX* with a CD* matrix.

**Comment by djperrefort** [comment]
To double check my understanding: CRPIX is the image coordinate of a reference pixel, CRVAL is the real world coordinate of that pixel, and CD represents the coordinate increments between pixels?
