### ISSUE TITLE
Feedback needed on tables tutorial

### ISSUE THREAD

**Issue by djperrefort** [mwvgroup/Tutorials#6]
General feedback is needed on the recently added tutorial on reading and manipulating tables, including any comments on content, organization, and / or clarity. This can wait to be completed until after finals.

**Comment by burkfm** [comment]
The table tutorial and photometry introduction is really quite informative overall. I feel that a few minor grammar edits along with some clarification on apertures will improve the tutorials.

**Comment by djperrefort** [comment]
Before I approve the pull request, what in particular about the apertures was unclear?

**Comment by burkfm** [comment]
I did not know what an aperture was. In the "Point Spread Function" Section, I changed "draw an aperture" to "draw a circle" to try to make the identity of the aperture clearer, but I think a more formal definition of an aperture earlier would dispel any confusion.


Francis

________________________________
